### ISSUE TITLE
Use stateful set to ensure there is only one pod running for a pipeline

### ISSUE THREAD

**Issue by ming535** [moiot/gravity-operator#2]
Make sure old pod are absolutely terminated before new pod created.

We can use [leader for life](https://github.com/operator-framework/operator-sdk/blob/master/pkg/leader/leader.go) to have a master-hotstandby to minimize the MTTR of a pipeline; but that is not the priority right now.

[k8s pod safety in statefulset](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/storage/pod-safety.md)

**Comment by Ryan-Git** [comment]
[ref](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods)
> (simultaneous with 3) Pod is removed from endpoints list for service, and are **no longer considered part of the set of running pods for replication controllers**.

**Comment by ming535** [comment]
Make sure to test this case with network partition. The simplest way to test is like this:

1. In a k8s cluster with multiple worker nodes, create a Statefulset with 1 replica

2. Log into the node with pipeline running, shutdown the `eth0` with `ifconfig eth0 down`

3. Observe and make sure that there is no pod scheduled to other worker nodes.

Do the same for `Deployment`, we should observe that the pod scheduled to other worker nodes eventually.
