### ISSUE TITLE
Issues using gravity-operator

### ISSUE THREAD

**Issue by MarkHaakman** [moiot/gravity-operator#29]
Hi,

I recently discovered Gravity and I managed to one instance working. Now, I want to run multiple instances of gravity at once, so I tried using gravity-operator.

I got everything running in a Kubernetes cluster, and I can access gravity-admin via the browser. I'm not able to get an instance running though. Issues I'm having:

1. You have a REST API, but where can I find the documentation? I have found https://github.com/moiot/gravity/blob/master/docs/wip_developer_guide.md , but there you refer to a configuration in `$drc_workspace/specs_example.json` which I cannot find. 
2. In the Web interface of gravity-admin, I should be able to create a new pipeline. The format required is json, while all your documentation describes the toml format. How should the json configuration file be formatted? I used a toml to json converter, but then I get the error `create pipeline failed.. err: null`.

It would be amazing if you could help me with these issues.

**Comment by Ryan-Git** [comment]
Hi MarkHaakman, 

Sorry for the lack of documentation.  Currently there's no doc for the rest api. You could refer to code [here](https://github.com/moiot/gravity-operator/blob/master/pkg/apiserver/api_server.go).

There's a few tricky part when creating. Most of the toml equivalent configuration should be put into `spec.config` field since we follow k8s conventions. And name of the task should be put into `metadata.name`. Here's an example
```json
{
  "metadata": {
    "name": "{any dns compatible name unique across the cluster}"
  },
  "spec": {
    "config": {
      "version": "1.0",
      "input": {
        "type": "mysql",
        "mode": "stream",
        "config": {
          "source": {
            "host": "xxx",
            "password": "",
            "port": 3306,
            "username": "root"
          }
        }
      },
      "output": {
        "type": "mysql",
        "config": {
          "routes": [
            {
              "match-schema": "{source schema}",
              "match-table": "*",
              "target-schema": "{target schema}"
            }
          ],
          "target": {
            "host": "xxx",
            "password": "",
            "port": 3306,
            "username": "root"
          }
        }
      }
    }
  }
}
```

**Comment by MarkHaakman** [comment]
Thank you for your help! I got everything running successfully now.
