### ISSUE TITLE
Question regarding unique server ids for MySQL

### ISSUE THREAD

**Issue by MarkHaakman** [moiot/gravity-operator#30]
Is it important for the working of Gravity that each MySQL server has a unique server_id in its configuration, or does it not matter?

I mean the following MySQL configuration item:
```
[mysqld]
server_id=4
```

Thank you!

**Comment by Ryan-Git** [comment]
It's mandatory. gravity needs binary logging and works as a MySQL slave. As [MySQL doc](https://dev.mysql.com/doc/refman/5.7/en/replication-options.html) mentioned:

> In MySQL 5.7, server_id must be specified if binary logging is enabled, otherwise the server is not allowed to start.

> server_id is set to 0 by default. On a replication master and each replication slave, you must specify server_id to establish a unique replication ID in the range from 1 to 232 − 1.

**Comment by MarkHaakman** [comment]
Thanks!
